Repository cucumber/cucumber-jvm, pull requests merged in 2020-10, with the labels that each got.

#2144 Do not send headers after following redirection
  CHANGELOG.md
  core/src/main/java/io/cucumber/core/plugin/UrlOutputStream.java
  core/src/test/java/io/cucumber/core/plugin/UrlOutputStreamTest.java
Labels: type: bug

#2156 Update JUnit Platform Engine documentation
  junit-platform-engine/README.md
Labels: hacktoberfest-accepted

#2154 Replace Travis CI with Github Actions #2147
  .github/workflows/.toolchains.xml
  .github/workflows/build.yml
  .travis.yml
  README.md
  RELEASING.md
Labels: hacktoberfest-accepted

#2162 Migrate from coverall to codecov
  .github/workflows/build.yml
  README.md
  examples/pom.xml
  java/pom.xml
  java8/pom.xml
  pom.xml
Labels: hacktoberfest-accepted

#2167 Fix typos, minor edits
  java/README.md
Labels: Hacktoberfest, hacktoberfest-accepted
